import { Hero } from './hero';

export const HEROES: Hero[] = [
    {
        id: 1, 
        name: 'A',
        age: 21,
        gender: 'Male',
        power: 'A',
        rank: 'S',
        squadId: 1,
        isSquadLeader: true,
    },
    {
        id: 2, 
        name: 'B',
        age: 18,
        gender: 'Female',
        power: 'B',
        rank: 'S',
        squadId: 2,
        isSquadLeader: true,
    },
    {
        id: 3, 
        name: 'C',
        age: 24,
        gender: 'Male',
        power: 'C',
        rank: 'S',
        squadId: 3,
        isSquadLeader: true,
    },
    {
        id: 4, 
        name: 'D',
        age: 21,
        gender: 'Fmale',
        power: 'D',
        rank: 'S',
        squadId: 4,
        isSquadLeader: true,
    },
    {
        id: 5, 
        name: 'E',
        age: 21,
        gender: 'Male',
        power: 'E',
        rank: 'S',
        squadId: 5,
        isSquadLeader: true,
    },
    {
        id: 6, 
        name: 'F',
        age: 21,
        gender: 'Male',
        power: 'F',
        rank: 'S',
        squadId: 6,
        isSquadLeader: true,
    },
    {
        id: 7, 
        name: 'G',
        age: 17,
        gender: 'Female',
        power: 'G',
        rank: 'A',
        squadId: 1,
        isSquadLeader: false,
    },
    {
        id: 8, 
        name: 'H',
        age: 21,
        gender: 'Male',
        power: 'H',
        rank: 'B',
        squadId: 1,
        isSquadLeader: false,
    },
    {
        id: 9, 
        name: 'I',
        age: 21,
        gender: 'Male',
        power: 'I',
        rank: 'C',
        squadId: 2,
        isSquadLeader: false,
    },
    {
        id: 10, 
        name: 'J',
        age: 21,
        gender: 'Male',
        power: 'J',
        rank: 'D',
        squadId: 2,
        isSquadLeader: false,
    },
    {
        id: 11, 
        name: 'K',
        age: 26,
        gender: 'Male',
        power: 'K',
        rank: 'E',
        squadId: 2,
        isSquadLeader: false,
    },
    {
        id: 12, 
        name: 'L',
        age: 21,
        gender: 'Male',
        power: 'L',
        rank: 'F',
        squadId: 2,
        isSquadLeader: false,
    },
    {
        id: 13, 
        name: 'M',
        age: 21,
        gender: 'Male',
        power: 'M',
        rank: 'A',
        squadId: 3,
        isSquadLeader: false,
    },
    {
        id: 14, 
        name: 'N',
        age: 21,
        gender: 'Male',
        power: 'N',
        rank: 'B',
        squadId: 3,
        isSquadLeader: false,
    },
    {
        id: 15,
        name: 'O',
        age: 23,
        gender: 'Fale',
        power: 'O',
        rank: 'C',
        squadId: 3,
        isSquadLeader: false,
    },
    {
        id: 16,
        name: 'P',
        age: 21,
        gender: 'Male',
        power: 'P',
        rank: 'D',
        squadId: 3,
        isSquadLeader: false,
    },
    {
        id: 17, 
        name: 'Q',
        age: 21,
        gender: 'Male',
        power: 'Q',
        rank: 'E',
        squadId: 3,
        isSquadLeader: false,
    },
    {
        id: 18, 
        name: 'R',
        age: 21,
        gender: 'Male',
        power: 'R',
        rank: 'F',
        squadId: 4,
        isSquadLeader: false,
    },
    {
        id: 19, 
        name: 'S',
        age: 21,
        gender: 'Female',
        power: 'S',
        rank: 'A',
        squadId: 4,
        isSquadLeader: false,
    },
    {
        id: 20, 
        name: 'T',
        age: 22,
        gender: 'Male',
        power: 'T',
        rank: 'B',
        squadId: 4,
        isSquadLeader: false,
    },
    {
        id: 21, 
        name: 'U',
        age: 21,
        gender: 'Male',
        power: 'U',
        rank: 'C',
        squadId: 4,
        isSquadLeader: false,
    },
    {
        id: 22, 
        name: 'V',
        age: 19,
        gender: 'Female',
        power: 'V',
        rank: 'D',
        squadId: 4,
        isSquadLeader: false,
    },
    {
        id: 23, 
        name: 'W',
        age: 21,
        gender: 'Male',
        power: 'W',
        rank: 'D',
        squadId: 4,
        isSquadLeader: false,
    },
    {
        id: 24, 
        name: 'X',
        age: 21,
        gender: 'Male',
        power: 'X',
        rank: 'E',
        squadId: 4,
        isSquadLeader: false,
    },
    {
        id: 25, 
        name: 'Y',
        age: 21,
        gender: 'Male',
        power: 'Y',
        rank: 'F',
        squadId: 4,
        isSquadLeader: false,
    },
    {
        id: 26, 
        name: 'Z',
        age: 25,
        gender: 'Male',
        power: 'Z',
        rank: 'A',
        squadId: 4,
        isSquadLeader: false,
    },
];